questions =  [
    {"id": 0, "question": "Freedom of business is the best practical way a society can prosper.", "effects": {"right": 1, "auth": -1}},
    {"id": 1, "question": "Charity is a better way of helping those in need than social welfare.", "effects": {"right": 1}},
    {"id": 2, "question": "Wages are always fair, as employers know best what a worker's labour is worth.", "effects": {"right": 1}},
    {"id": 3, "question": "It is \"human nature\" to be greedy.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Exploitation\" is an outdated term, as the struggles of 1800s capitalism don't exist anymore.", "effects": {"right": 1}},
    {"id": 5, "question": "Communism is an ideal that can never work in practice.", "effects": {"right": 1}},
    {"id": 6, "question": "Taxation of the wealthy is a bad idea, society would be better off without it.", "effects": {"right": 1}},
    {"id": 7, "question": "The harder you work, the more you progress up the social ladder.", "effects": {"right": 1}}, 
    {"id": 8, "question": "Goverment intervention is a threat to the economy.", "effects": {"right": 1}},
    {"id": 9, "question": "Healthcare should be privatised.", "effects": {"right": 1}},
    {"id": 10, "question": "Monopolies wouldn't exist in a true freemarket.", "effects": {"right": 1}},
    {"id": 11, "question": "Organisations and corporations cannot be trusted and need to be regulated by the government.", "effects": {"right": -1, "auth": 1}},
    {"id": 12, "question": "A government that provides for everyone is an inherently good idea.", "effects": {"right": -1}},
    {"id": 13, "question": "The current welfare system should be expanded to further combat inequality.", "effects": {"right": -1}},
    {"id": 14, "question": "Land should not be a commodity to be bought and sold.", "effects": {"right": -1}},
    {"id": 15, "question": "All industry should be nationalised.", "effects": {"right": -1}},
    {"id": 16, "question": "The bank should be nationalised.", "effects": {"right": -1}},
    {"id": 16, "question": "Class is the primary division of society.", "effects": {"right": -1}},
    {"id": 17, "question": "Economic inequality is too high in the world.", "effects": {"right": -1}},
    {"id": 18, "question": "Opression by corporations is more of a concern than oppression by the government.", "effects": {"right": -1}},
    {"id": 19, "question": "From each according to his ability, to each according to his need.", "effects": {"right": -1}},
    {"id": 20, "question": "the workers should own the means of production.", "effects": {"right": -1}},
    {"id": 21, "question": "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.", "effects": {"auth": 1}},
    {"id": 22, "question": "Authority figures, if morally correct, are a good thing for society.", "effects": {"auth": 1}},
    {"id": 23, "question": "Strength is necessary for any government to succeed.", "effects": {"auth": 1}},
    {"id": 24, "question": "Only the government can fairly and effectively regulate organisations.", "effects": {"auth": 1, "right": -1}},
    {"id": 25, "question": "Society requires structure and bureaucracy in order to function.", "effects": {"auth": 1}},
    {"id": 26, "question": "Mandatory IDs should be used to ensure public safety.", "effects": {"auth": 1}},
    {"id": 27, "question": "In times of crisis, safety becomes more important than civil liberties.", "effects": {"auth": 1}},
    {"id": 28, "question": "If you have nothing to hide, you have nothing to fear.", "effects": {"auth": 1}},
    {"id": 29, "question": "all citizens should be drafted into the army.", "effects": {"auth": 1}},
    {"id": 30, "question": "Everything within the state, nothing outside the state, nothing against the state.", "effects": {"auth": 1}},
    {"id": 31, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -1}},
    {"id": 32, "question": "Without democracy, a society is nothing.", "effects": {"auth": -1}},
    {"id": 33, "question": "Jury nullification should be legal.", "effects": {"auth": -1}},
    {"id": 34, "question": "The smaller the government, the freer the people.", "effects": {"auth": -1, "right": 1}},
    {"id": 35, "question": "The government should, at most, provide emergency services and law enforcement.", "effects": {"auth": -1}},
    {"id": 36, "question": "The police were not created to protect the people, but to uphold the status quo by force.", "effects": {"auth": -1}},
    {"id": 37, "question": "State schools are a bad idea because our state shouldn't be influencing our children.", "effects": {"auth": -1}},
    {"id": 38, "question": "The State is inherently authoritarian.", "effects": {"auth": -1}},
    {"id": 39, "question": "The UN should be given more power to more adequately enforce it's resolutions.", "effects": {"auth": -1}},
    {"id": 40, "question": "All authority should be questioned.", "effects": {"auth": -1, "prog": 1}},
    {"id": 41, "question": "Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.", "effects": {"prog": 1}},
    {"id": 42, "question": "An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"prog": 1, "auth": -1}},
    {"id": 43, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"prog": 1}},
    {"id": 44, "question": "Nudism is perfectly natural.", "effects": {"prog": 1}},
    {"id": 45, "question": "Animals deserve certain universal rights.", "effects": {"prog": 1}},
    {"id": 46, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"prog": 1}},
    {"id": 47, "question": "Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"prog": 1}},
    {"id": 48, "question": "Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"prog": 1}},
    {"id": 49, "question": "Environmental regulations are essential.", "effects": {"prog": 1, "right": -1}},
    {"id": 50, "question": "Assisted suicide should be legal.", "effects": {"prog":1}},
    {"id": 51, "question": "Queerism is against my values.", "effects": {"prog": -1}},
    {"id": 52, "question": "Queer individuals should not be able to adopt children.", "effects": {"prog": -1}},
    {"id": 53, "question": "Drugs are harmful and should be banned.", "effects": {"prog": -1}},
    {"id": 54, "question": "The death penalty should exist for certain crimes.", "effects": {"prog": -1}},
    {"id": 55, "question": "Victimless crimes should still be punished.", "effects": {"prog": -1}},
    {"id": 56, "question": "One cannot be moral without religion.", "effects": {"prog": -1}},
    {"id": 57, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"prog": -1}},
    {"id": 58, "question": "Multiculturalism is bad.", "effects": {"prog": -1}},
    {"id": 59, "question": "Religious authority shouldn't be questioned.", "effects": {"prog": -1, "auth": 1}},
    {"id": 60, "question": "Illegal immigrants should be deported.", "effects": {"prog": -1}}
];
